import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ChevronRight,Clock3,Plane,ShieldCheck,Sparkles,Users} from 'lucide-react';
import {api} from './api';
import type {Candidate,Disruption,Flight,Recovery} from './types';

const disruptionFallback:Disruption={id:'DSP-ORD-0726',severity:'critical',title:'ORD ground stop cascades through Midwest network',summary:'Thunderstorm cell closed departures until 19:40Z. SkySolver is repairing crew, aircraft, gate and passenger dependencies across four hubs.',source:'NOAA / airport flow control',confidence:.96,started_at:'2026-07-31T17:58:00Z',deadline:'2026-07-31T19:40:00Z',partitions:['ORD','DEN','DFW','BOS'],affected_flights:['SK418','SK226','SK902','SK141','SK626','SK709'],illegal_crews:7,blocked_aircraft:4,passengers:1284,status:'active'};
const flightFallback:Flight={id:'SK418',origin:'ORD',destination:'DEN',aircraft:{registration:'N123SK',type:'A321',status:'blocked'},gate:'C14',proposed_gate:'C16',crew:{id:'C-184',status:'illegal',duty_remaining:'-00:38',qualifications:['A321']},passengers:186,connections:42,delay:92,state:'recovery_pending',tier:'tier1',risk:'critical'};
const flights=[['SK418','DEN','A321','C14','186','92'],['SK226','BOS','B737','B08','149','74'],['SK902','MCO','A320','C10','162','48'],['SK141','SEA','B738','B11','175','35'],['SK626','SFO','A321','C16','168','31'],['SK709','ATL','A320','B21','154','27']];

function AirportView({flight,deployed}:{flight:Flight;deployed:boolean}){return <div className="airport-view">
  <div className="airport-title"><span>Operational view — Chicago O’Hare (ORD)</span><span className="live"><i/>Live surface</span></div>
  <svg viewBox="0 0 760 330" role="img" aria-label="ORD gate, taxiway and runway recovery plan">
    <defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="#17303b" strokeWidth="1"/></pattern></defs>
    <rect width="760" height="330" fill="url(#grid)"/><path className="runway" d="M180 304L752 60"/><path className="runway-mark" d="M195 298L744 64"/>
    <path className="taxi" d="M90 62H290Q330 62 330 102V226Q330 258 363 270L500 212L640 145"/><path className="taxi-center" d="M90 62H290Q330 62 330 102V226Q330 258 363 270L500 212L640 145"/>
    <path className="taxi" d="M90 132H245Q275 132 275 165V254M90 202H220Q245 202 245 232V274M500 212L470 170M640 145L608 104"/><path className="taxi-center" d="M90 132H245Q275 132 275 165V254M90 202H220Q245 202 245 232V274M500 212L470 170M640 145L608 104"/>
    <path className={deployed?'route deployed':'route'} d="M90 62H290Q330 62 330 102V226Q330 258 363 270L500 212L640 145"/>
    {['C14','C19','B08','B11'].map((g,i)=><g className="gate" key={g}><rect x="20" y={44+i*69} width="70" height="38" rx="4"/><text x="42" y={68+i*69}>{g}</text></g>)}
    <g className="plane active" transform={`translate(${deployed?500:104} ${deployed?212:62})`}><circle r="17"/><Plane size={18}/><text x="27" y="-2">{flight.id}</text><text x="27" y="13">{deployed?'TAXI OUT':'DEPARTURE PENDING'}</text></g>
    <g className="plane warn" transform="translate(104 132)"><circle r="15"/><Plane size={16}/><text x="25" y="3">SK226 · CREW SEARCH</text></g>
    <g className="plane good" transform="translate(363 270)"><circle r="15"/><Plane size={16}/><text x="25" y="3">SK141 · RECOVERED</text></g>
    <g className="hold"><path d="M344 253l18 25M351 248l18 25"/><text x="380" y="290">HOLD SHORT 27L</text></g><text className="label" x="687" y="89">EXIT E5</text><text className="label" x="176" y="321">27L</text>
  </svg>
 </div>}

function Checks({validated}:{validated:boolean}){return <div className="checks"><h3>Legality checks</h3>{[['Crew','Legal'],['Aircraft','Legal'],['Operations',validated?'144 checks passed':'Ready to validate']].map(([a,b])=><div key={a}><span className="check"><Check size={14}/></span><strong>{a}</strong><span>{b}</span><ChevronRight size={15}/></div>)}</div>}

const destinations:Record<string,{x:number;y:number;city:string}>={DEN:{x:505,y:92,city:'Denver'},BOS:{x:650,y:54,city:'Boston'},MCO:{x:590,y:205,city:'Orlando'},SEA:{x:105,y:48,city:'Seattle'},SFO:{x:80,y:145,city:'San Francisco'},ATL:{x:555,y:168,city:'Atlanta'}};
function RouteMap({flight}:{flight:Flight}){const end=destinations[flight.destination]||destinations.DEN;return <div className="route-map"><div className="route-map-title"><span>Planned route</span><strong>{flight.origin} <ArrowRight size={12}/> {flight.destination}</strong></div><svg viewBox="0 0 700 235" role="img" aria-label={`${flight.id} planned route from ${flight.origin} to ${flight.destination}`}><path className="land" d="M54 45L118 27l71 15 44-14 62 20 85-10 81 14 90-6 82 26-7 38-34 22-4 42-56 24-64-11-41 28-76-7-54 17-69-28-70 3-46-28 8-43-25-30z"/><path className="state-lines" d="M162 34l13 151M258 34l4 174M358 42l-3 164M456 45l-4 153M548 55l-7 132M83 103l534 2M72 154l522 1"/><path className="flight-path" d={`M390 75 Q${(390+end.x)/2} ${Math.min(15,end.y-40)} ${end.x} ${end.y}`}/><circle className="airport-dot" cx="390" cy="75" r="7"/><circle className="airport-ring" cx="390" cy="75" r="12"/><circle className="airport-dot destination" cx={end.x} cy={end.y} r="7"/><circle className="airport-ring" cx={end.x} cy={end.y} r="12"/><g className="route-plane" transform={`translate(${390+(end.x-390)*.7} ${75+(end.y-75)*.7}) rotate(${Math.atan2(end.y-75,end.x-390)*180/Math.PI})`}><Plane size={23}/></g><text x="365" y="61">ORD</text><text x="352" y="92">Chicago</text><text x={end.x+18} y={end.y-4}>{flight.destination}</text><text x={end.x+18} y={end.y+14}>{end.city}</text></svg><footer><span>No changes to routing.</span><span>{flight.id} · {flight.aircraft.type}</span></footer></div>}

export default function App(){
 const[disruption,setDisruption]=useState(disruptionFallback),[flight,setFlight]=useState(flightFallback),[recovery,setRecovery]=useState<Recovery|null>(null),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[clock,setClock]=useState('');
 useEffect(()=>{api.disruptions().then(r=>r.items[0]&&setDisruption(r.items[0])).catch(()=>{});api.flight('SK418').then(setFlight).catch(()=>{});const t=setInterval(()=>setClock(new Date().toISOString().slice(11,16)+'Z'),1000);return()=>clearInterval(t)},[]);
 const candidate:Candidate|undefined=useMemo(()=>recovery?.candidates.find(c=>c.id===selected)||recovery?.candidates.find(c=>c.recommended)||recovery?.candidates[0],[recovery,selected]);
 async function act(fn:()=>Promise<{recovery:Recovery}>,success:string){setBusy(true);setMessage('');try{const r=await fn();setRecovery(r.recovery);const choice=r.recovery.selected_candidate_id||r.recovery.candidates.find(c=>c.recommended)?.id||r.recovery.candidates[0]?.id||null;setSelected(choice);setMessage(success)}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
 const primary=async()=>{if(!recovery)return act(()=>api.createRecovery(disruption.id),'Recovery plan ready for review');if(!recovery.selected_candidate_id&&selected)return act(()=>api.decide(recovery.id,recovery.state_version,selected),'Plan approved');if(!recovery.validated)return act(()=>api.validate(recovery.id,recovery.state_version),'All hard rules passed');if(!recovery.deployed)return act(()=>api.deploy(recovery.id,recovery.state_version),'Recovery deployed');};
 const buttonLabel=!recovery?'Generate recovery plan':!recovery.selected_candidate_id?'Approve hold at gate':!recovery.validated?'Validate approved plan':!recovery.deployed?'Deploy recovery':'Recovery deployed';
 const solved=!!recovery, deployed=!!recovery?.deployed;
 return <main className="guided-occ">
  <header className="topbar"><div className="brand">SKYSOLVER <span>GUIDED RECOVERY</span></div><div className="top-status"><span className="healthy"><i/>System healthy</span><span>{clock||'09:41Z'}</span><span className="avatar">AJ</span></div></header>
  <section className="briefing"><div className="incident"><span className="priority">PRIORITY 1</span><h1>{disruption.title}</h1><p>{disruption.summary}</p></div><div className="metrics"><div><strong className="red">12</strong><span>Flights affected</span><small>↑ from 6</small></div><div><strong>1,284</strong><span>Passengers</span><small className="green">↓ 316 after rebooking</small></div><div><strong className="red">7</strong><span>Illegal crews</span><small>3 searches active</small></div><div><strong className="amber">4</strong><span>Aircraft blocked</span><small>2 swaps available</small></div></div></section>
  <section className="workspace">
   <aside className="flight-rail"><header><h2>Affected flights</h2><span>12 flights</span></header><div className="flight-list">{flights.map(([id,dest,type,gate,pax,delay])=><button key={id} className={flight.id===id?'selected':''} onClick={()=>api.flight(id).then(setFlight).catch(()=>{})}><Plane size={20}/><span><strong>{id}</strong><b>ORD <ArrowRight size={11}/> {dest}</b><small>{type} · Gate {gate} · Pax {pax}</small></span><em>+{delay} min</em></button>)}</div><button className="more">+6 more flights</button><footer><Clock3 size={15}/>Last updated 2 min ago</footer></aside>
   <section className="flight-workspace"><header className="flight-head"><div><h2>{flight.id}</h2><span>{flight.origin} <ArrowRight size={14}/> {flight.destination}</span><small>{flight.aircraft.type} · Tail {flight.aircraft.registration}</small></div><strong className="delay">Delay: +{flight.delay} min</strong></header>
    <AirportView flight={flight} deployed={deployed}/>
    <section className="plan-explainer"><header><div><h3>{solved?'Recovery plan — Hold for 27 minutes at Chicago (ORD)':'What SkySolver is evaluating'}</h3><p>{solved?'This plan resolves the downstream conflict without changing aircraft or rebooking passengers.':'Crew legality, aircraft availability, passenger connections and gate conflicts are being evaluated together.'}</p></div>{solved&&<button>Why this plan <ChevronRight size={15}/></button>}</header>
     <div className="before-after"><div><span>Before plan</span><small>Arrives DEN</small><strong className="red">14:35 <em>(+92 min)</em></strong><p>Departs ORD <b>13:00</b> · Gate arrival <b>15:20</b></p></div><ArrowRight className="change-arrow"/><div><span className="green">After plan</span><small>Arrives DEN</small><strong>{solved?'15:27':'—'} <em className="green">{solved?'On time':''}</em></strong><p>Departs ORD <b>{solved?'13:27':'—'}</b> · Gate arrival <b>{solved?'16:12':'—'}</b></p></div></div>
     <RouteMap flight={flight}/><div className="what-changes"><strong>What changes</strong><span>{solved?'Aircraft holds at ORD gate for 27 minutes, then follows the planned route shown above.':'Generate a plan to see the exact operational change.'}</span></div>
    </section>
   </section>
   <aside className="action-rail"><header><h2>Recommended action</h2><span className="priority">PRIORITY 1</span></header><div className="recommendation"><h3>{solved?'Hold '+flight.id+' at gate for 27 minutes':'Repair '+flight.id+' and linked resources'}</h3><p>{solved?'Resume pushback at 13:27 CT.':'SkySolver will race legal solver tiers and return the first acceptable recovery.'}</p><div className="outcome"><span><Users size={19}/><b>{flight.passengers} passengers</b><small>{solved?'No rebooking required':'Passenger impact included'}</small></span><span><Clock3 size={19}/><b>{solved?'Delay reduced by 65 minutes':'Current delay +'+flight.delay+' minutes'}</b><small>{solved?'New arrival 15:27':'Awaiting recovery plan'}</small></span></div><Checks validated={!!recovery?.validated}/><button className="primary" disabled={busy||deployed} onClick={primary}>{busy?<><Sparkles className="spin" size={17}/>Working…</>:deployed?<><Check size={18}/>Recovery deployed</>:<>{buttonLabel}<ArrowRight size={17}/></>}</button>{recovery&&!recovery.deployed&&<small className="expiry">Plan expires in 04:32</small>}{message&&<p className="message"><ShieldCheck size={14}/>{message}</p>}</div></aside>
  </section>
  <footer className="footerbar"><span><i/>Next update in 60s</span><span>Auto-updates on</span><button>Need help?</button></footer>
 </main>;
}
