import{useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,ArrowRight,Check,CloudLightning,Cpu,Database,Gauge,GitBranch,History,Map,Plane,ShieldCheck,Users,Wrench,X}from'lucide-react';
import{api,ApiError}from'./api';
import type{Audit,Disruption,Flight,Recovery}from'./types';
import RouteWorkspace from'./RouteWorkspace';
import SolverWorkspace from'./SolverWorkspace';
import Tier3Workspace from'./Tier3Workspace';
import DataHealthWorkspace from'./DataHealthWorkspace';

type Route='overview'|'datahealth'|'disruptions'|'crew'|'flights'|'aircraft'|'routes'|'tiers'|'tier1'|'tier2'|'tier3'|'decisions'|'deployment'|'audit';
const nav:[Route,string,any,boolean?][]=[['overview','Overview',Activity],['datahealth','Data Health',Database],['disruptions','Disruptions',CloudLightning],['crew','Crew Recovery',Users],['flights','Flights',Plane],['aircraft','Aircraft',Wrench],['routes','Planned Routes',Map],['tiers','Solver Tiers',GitBranch],['tier1','Tier 1 · Legal',Gauge,true],['tier2','Tier 2 · Optimize',Cpu,true],['tier3','Tier 3 · Human',Users,true],['decisions','Decisions',ShieldCheck],['deployment','Deployment',ArrowRight],['audit','Audit',History]];
const fallbackDisruption:Disruption={id:'DSP-DEL-0726',severity:'critical',title:'Delhi low-visibility scenario',summary:'Synthetic disruption fixture for workflow evaluation.',source:'Scenario fixture',confidence:.96,started_at:'2026-07-31T00:28:00Z',deadline:'2026-07-31T02:10:00Z',partitions:['DEL','BOM','BLR','HYD'],affected_flights:['AI421','6E203','UK945','AI807','6E531'],illegal_crews:2,blocked_aircraft:2,passengers:958,status:'active'};
const fallbackFlight:Flight={id:'AI421',origin:'DEL',destination:'BOM',aircraft:{registration:'VT-EXA',type:'A321',status:'blocked'},gate:'T3-42',proposed_gate:'T3-46',crew:{id:'IC-184',status:'illegal',duty_remaining:'-00:38',qualifications:['A321']},passengers:186,connections:42,delay:92,state:'recovery_pending',tier:'tier1',risk:'critical'};
const flightIds=['AI421','6E203','UK945','AI807','6E531'];

function Badge({children,tone='neutral'}:{children:any;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function PageHead({eyebrow,title,detail,actions}:{eyebrow:string;title:string;detail:string;actions?:any}){return <header className="page-head"><div><span>{eyebrow}</span><h1>{title}</h1><p>{detail}</p></div><div className="page-actions">{actions}</div></header>}
function Table({headers,rows,onRow}:{headers:string[];rows:any[][];onRow?:(row:any[])=>void}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className={onRow?'clickable':''} onClick={()=>onRow?.(row)}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}
function Provenance(){return <div className="provenance"><AlertTriangle/><span><strong>SYNTHETIC DEMO — NOT FOR OPERATIONAL USE</strong><small>Source: skysolver-scenario-fixture · state v1 · fixture data · carrier publishing disabled</small></span></div>}

function Overview({d,recovery,go}:{d:Disruption;recovery:Recovery|null;go:(r:Route)=>void}){const metrics=[['Recovery',recovery?`${recovery.progress}%`:'Not solved'],['Affected flights',String(d.affected_flights.length)],['Illegal crews',String(d.illegal_crews)],['Blocked aircraft',String(d.blocked_aircraft)],['Passenger exposure',d.passengers.toLocaleString('en-IN')],['Candidate plans',String(recovery?.candidates.length||0)]];return <><PageHead eyebrow="SYNTHETIC NETWORK BRIEFING" title="India recovery workflow evaluation" detail="Scenario data exercises the recovery workflow; it is not connected to a carrier." actions={<button className="primary" onClick={()=>go('crew')}>Open recovery worklist</button>}/><div className="kpis">{metrics.map(([label,value])=><div className="kpi" key={label}><span>{label}</span><strong>{value}</strong><small>Scenario fixture</small></div>)}</div><div className="overview-grid"><section className="card urgent"><header><div><Badge tone="danger">P1 · SYNTHETIC</Badge><h2>{d.title}</h2></div></header><p>{d.summary}</p><button onClick={()=>go('disruptions')}>Inspect scenario</button></section><section className="card"><h2>What requires action</h2><div className="impact-list"><span><b>AI421 crew legality</b><strong>Review</strong></span><span><b>UK945 qualification</b><strong>Review</strong></span><span><b>Carrier publication</b><strong>Disabled</strong></span></div></section></div></>}

function Disruptions({d,run,busy}:{d:Disruption;run:()=>void;busy:boolean}){return <><PageHead eyebrow={`DISRUPTION ${d.id}`} title={d.title} detail={d.summary} actions={<button className="primary" disabled={busy} onClick={run}>Run synthetic recovery</button>}/><div className="fact-strip">{[['Source',d.source],['Confidence',`${Math.round(d.confidence*100)}%`],['Operating mode','Fixture'],['Partitions',d.partitions.join(', ')],['Affected',String(d.affected_flights.length)],['Authority','None']].map(x=><span key={x[0]}>{x[0]}<b>{x[1]}</b></span>)}</div><section className="card"><header><h2>Scenario scope</h2><Badge tone="warning">NOT LIVE</Badge></header><p>This scenario is fixed. Scope editing will return only after it is connected to versioned backend recovery inputs.</p></section></>}

function Crew({flight,setFlight,recovery,run,approve,validate,busy}:{flight:Flight;setFlight:(f:Flight)=>void;recovery:Recovery|null;run:()=>void;approve:()=>void;validate:()=>void;busy:boolean}){return <><PageHead eyebrow="CREW RECOVERY · SYNTHETIC" title="Scheduler review workspace" detail="Recommendations below come from executable synthetic solver artifacts." actions={<button className="primary" disabled={busy} onClick={run}>{recovery?'Re-run synthetic solve':'Run synthetic solve'}</button>}/><div className="crew-layout"><aside className="case-list">{flightIds.map(id=><button key={id} className={flight.id===id?'active':''} onClick={()=>api.flight(id).then(setFlight)}><Badge tone={id==='AI421'||id==='UK945'?'danger':'warning'}>{id==='AI421'||id==='UK945'?'P1':'P2'}</Badge><div><strong>{id}</strong><span>Scenario recovery case</span><small>Select for authoritative fixture state</small></div></button>)}</aside><section className="case-detail"><header><div><Badge tone={flight.crew.status==='illegal'?'danger':'warning'}>{flight.crew.status.toUpperCase()}</Badge><h2>{flight.id} · {flight.origin} → {flight.destination}</h2><p>{flight.aircraft.type} · {flight.aircraft.registration} · Gate {flight.gate}</p></div></header><div className="assignment-compare"><article><span>CURRENT FIXTURE ASSIGNMENT</span><h3>{flight.crew.id}</h3><dl><dt>Status</dt><dd>{flight.crew.status}</dd><dt>Duty remaining</dt><dd>{flight.crew.duty_remaining}</dd><dt>Qualification</dt><dd>{flight.crew.qualifications.join(', ')}</dd></dl></article><ArrowRight/><article className="proposed"><span>SOLVER ARTIFACT</span><h3>{recovery?.candidates[0]?.name||'Not generated'}</h3><p>{recovery?'Inspect the versioned candidate assignments on Decisions.':'Run the synthetic solver to generate evidence.'}</p></article></div></section><aside className="decision-panel"><header><span>DECISION STATE</span><Badge tone="cyan">SIMULATION</Badge></header><h2>{recovery?.selected_candidate_id?'Candidate selected':'No candidate selected'}</h2><p>Carrier publishing remains disabled until shadow-pilot safety gates are approved.</p>{!recovery?<button className="primary wide" onClick={run}>Generate artifacts</button>:!recovery.selected_candidate_id?<button className="primary wide" onClick={approve}>Select recommended artifact</button>:!recovery.validated?<button className="primary wide" onClick={validate}>Run demo legality checks</button>:<button className="wide" disabled>Demo legality checked · feasibility unavailable</button>}</aside></div></>}

function Flights({setFlight,go}:{setFlight:(f:Flight)=>void;go:(r:Route)=>void}){return <><PageHead eyebrow="FLIGHT OPERATIONS · FIXTURE" title="Scenario flights" detail="Select a flight to inspect its backend-provided movement record."/><section className="card"><Table headers={['Flight','Origin','Destination','Fleet','Tail','Crew status']} rows={flightIds.map(id=>[id,'—','—','—','—','Load record'])} onRow={r=>api.flight(r[0]).then(f=>{setFlight(f);go('routes')})}/></section></>}
function Aircraft(){return <><PageHead eyebrow="AIRCRAFT CONTROL · FIXTURE" title="Aircraft integration not connected" detail="Static swap claims have been removed until rotation and maintenance adapters provide authoritative feasibility."/><section className="empty"><Wrench/><h2>No authoritative aircraft feed</h2><p>Connect the aircraft operations and MRO adapters to enable this workspace.</p></section></>}

function Decisions({recovery,run,choose}:{recovery:Recovery|null;run:()=>void;choose:(id:string)=>void}){return <><PageHead eyebrow="RECOVERY DECISIONS · SIMULATION" title="Solver-produced candidate artifacts" detail="Every candidate carries solver, input snapshot, ruleset and state provenance." actions={<button onClick={run}>{recovery?'Re-run solve':'Generate artifacts'}</button>}/>{!recovery?<section className="empty"><ShieldCheck/><h2>No candidate artifacts</h2><p>Run the synthetic recovery to create executable solver output.</p></section>:<div className="candidate-grid">{recovery.candidates.map(c=><article className="candidate" key={c.id}><header><Badge tone={c.recommended?'cyan':'neutral'}>{c.tier?.toUpperCase()||'SOLVER'}</Badge><strong>{c.id}</strong></header><h2>{c.name}</h2><div className="score">{Math.round(c.coverage*100)}%<span>fixture coverage</span></div><div className="candidate-metrics"><span>Flights<b>{c.flights_recovered}</b></span><span>Unresolved<b>{c.warnings.length}</b></span><span>Risk<b>{c.risk}</b></span></div><div className="explain"><strong>Evidence</strong><p>{c.changes.join('. ')}</p><small>{c.ruleset_version||'Ruleset unavailable'} · state v{c.state_version||recovery.state_version}</small></div><button onClick={()=>choose(c.id)}>Select artifact</button></article>)}</div>}</>}

function Deployment({recovery}:{recovery:Recovery|null}){return <><PageHead eyebrow="DEPLOYMENT SIMULATION" title="Carrier publishing disabled" detail="No crew, aircraft, gate or passenger command will be sent from this environment."/><section className="card deploy-summary"><header><div><Badge tone="warning">SHADOW GATE NOT APPROVED</Badge><h2>{recovery?.selected_candidate_id||'No selected candidate'}</h2></div><strong>State v{recovery?.state_version||'—'}</strong></header><div className="deploy-gates">{[['Candidate selected',!!recovery?.selected_candidate_id],['Demo legality checks',!!recovery?.validated],['Joint feasibility',false],['Certified validation service',false],['Carrier adapter',false],['Safety approval',false]].map(([label,pass])=><span key={String(label)} className={pass?'pass':''}>{pass?<Check/>:<AlertTriangle/>}<b>{label}</b><small>{pass?'Available':'Blocked'}</small></span>)}</div></section></>}
function AuditPage({items}:{items:Audit[]}){return <><PageHead eyebrow="DEMO AUDIT" title="Mutable demonstration event history" detail="This local JSON ledger is not immutable, WORM-compliant or suitable for regulatory evidence."/><section className="card"><Table headers={['Timestamp','Action','Actor','Recovery','Detail','Ruleset']} rows={items.map(a=>[new Date(a.timestamp).toLocaleString(),a.action.replaceAll('_',' '),a.operator,a.recovery_id,a.detail,a.ruleset_version])}/>{!items.length&&<p>No demonstration events recorded.</p>}</section></>}

// Truthful, work-preserving messaging for mutation failures. A 409 never discards
// the operator's context: we keep the current recovery selection and refresh the
// authoritative state so the action can be retried against the current version.
export function describeFailure(error:unknown,recovery:Recovery|null,setRecovery:(r:Recovery)=>void):string{
 if(error instanceof ApiError){
  if(error.isStale){if(recovery)api.recovery(recovery.id).then(setRecovery).catch(()=>{});return `Plan advanced to state v${error.stateVersion??'?'} elsewhere. Your selection is preserved — review the refreshed state and retry.`}
  if(error.isValidation)return `Backend rejected the request: ${error.ruleViolations.length} rule finding(s). No candidate was approved.`;
  if(error.isPermission)return 'Not authorized for this action. Approval and deployment require stepped-up authentication.';
  return error.correlationId?`${error.message} (correlation ${error.correlationId})`:error.message;
 }
 return error instanceof Error?error.message:'Action failed';
}

export default function App(){
 const routeFromHash=()=>((location.hash.slice(2)||'overview') as Route);
 const[route,setRoute]=useState<Route>(routeFromHash),[d,setD]=useState(fallbackDisruption),[flight,setFlight]=useState(fallbackFlight),[recovery,setRecovery]=useState<Recovery|null>(null),[audit,setAudit]=useState<Audit[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const onHash=()=>setRoute(routeFromHash());addEventListener('hashchange',onHash);api.disruptions().then(x=>x.items[0]&&setD(x.items[0])).catch(()=>{});api.flight('AI421').then(setFlight).catch(()=>{});api.audit().then(x=>setAudit(x.items)).catch(()=>{});return()=>removeEventListener('hashchange',onHash)},[]);
 const go=(next:Route)=>{location.hash=`/${next}`};
 const work=async(fn:()=>Promise<{recovery:Recovery}>,message:string)=>{setBusy(true);try{const result=await fn();setRecovery(result.recovery);setNotice(message);api.audit().then(x=>setAudit(x.items))}catch(error){setNotice(describeFailure(error,recovery,setRecovery))}finally{setBusy(false)}};
 const run=()=>work(()=>api.createRecovery(d.id),'Executable synthetic candidates generated');
 const choose=(id:string)=>recovery&&work(()=>api.decide(recovery.id,recovery.state_version,id),'Candidate artifact selected');
 const approve=()=>{const selected=recovery?.candidates.find(c=>c.recommended)||recovery?.candidates[0];if(selected)choose(selected.id)};
 const validate=()=>recovery?.selected_candidate_id&&work(()=>api.validate(recovery.id,recovery.state_version,recovery.selected_candidate_id||undefined),'Demo legality checks completed');
 const page=useMemo(()=>{switch(route){case'overview':return <Overview d={d} recovery={recovery} go={go}/>;case'datahealth':return <DataHealthWorkspace/>;case'disruptions':return <Disruptions d={d} run={run} busy={busy}/>;case'crew':return <Crew flight={flight} setFlight={setFlight} recovery={recovery} run={run} approve={approve} validate={validate} busy={busy}/>;case'flights':return <Flights setFlight={setFlight} go={go}/>;case'aircraft':return <Aircraft/>;case'routes':return <RouteWorkspace flight={flight} onFlight={setFlight}/>;case'tiers':return <SolverWorkspace onOpen={go}/>;case'tier1':case'tier2':return <SolverWorkspace selected={route} onOpen={go}/>;case'tier3':return <Tier3Workspace recovery={recovery} onRecovery={setRecovery} onStart={run}/>;case'decisions':return <Decisions recovery={recovery} run={run} choose={choose}/>;case'deployment':return <Deployment recovery={recovery}/>;case'audit':return <AuditPage items={audit}/>}},[route,d,flight,recovery,audit,busy]);
 return <main className="app-shell"><aside className="sidebar"><div className="logo"><span><Plane/></span><div>SKYSOLVER<small>India recovery evaluation</small></div></div><nav aria-label="Primary">{nav.map(([id,label,Icon,sub])=><button key={id} className={`${route===id||(id==='tiers'&&['tier1','tier2','tier3'].includes(route))?'active':''}${sub?' sub':''}`} aria-current={route===id?'page':undefined} onClick={()=>go(id)}><Icon/>{label}</button>)}</nav><div className="side-foot"><Badge tone="danger">NOT OPERATIONAL</Badge><span>Synthetic fixture</span><small>Carrier writes disabled</small></div></aside><section className="main"><Provenance/><div className="content">{page}</div></section>{notice&&<div className="toast"><ShieldCheck/>{notice}<button onClick={()=>setNotice('')}><X/></button></div>}</main>
}
