// @ts-nocheck -- API coordinates include a compatibility alias for the SVG map.
import{useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,Check,GitBranch,Map,Plane,RefreshCw,Users}from'lucide-react';
import{api}from'./api';
import type{Flight,PlannedRoute,RouteValidation}from'./types';

type Mode='flight'|'aircraft'|'crew'|'deadhead'|'changes'|'partition';
const modes:[Mode,string,any][]=[['flight','Flight route',Plane],['aircraft','Aircraft rotation',RefreshCw],['crew','Crew pairing',Users],['deadhead','Deadhead journey',ArrowRight],['changes','Recovery changes',GitBranch],['partition','Cross-partition',Map]];

export function routeArc(route:PlannedRoute,proposed=false){const{origin:o,destination:d}=route;return`M${o.x} ${o.y} Q${(o.x+d.x)/2+(proposed?30:0)} ${Math.min(o.y,d.y)-(proposed?55:37)} ${d.x} ${d.y}`}

function IndianMap({route}:{route:PlannedRoute}){const{o:ox,y:oy}=route.origin,{x:dx,y:dy}=route.destination;return <div className="india-map"><svg viewBox="0 0 760 470" role="img" aria-label={`${route.flight_id} ${route.origin.code} to ${route.destination.code} route over India`}><path className="india-land" d="M323 30l77 18 57 36 63 12 45 50 66 26 14 56-31 48-54 19-24 62-54 58-36-27-22 54-33-48-18-80-48-43-21-66-58-47 29-42-16-39 42-35 7-53 38-23 48 11z"/><path className="india-state" d="M351 57l12 91-46 63 42 58-14 91m91-282l-33 83 45 65-39 76 22 100m83-287l-56 82 64 60-41 86m-203-142l309 6m-263 83l258 5"/><path className="scheduled-line" d={routeArc(route)}/><path className="proposed-line" d={routeArc(route,true)}/><circle className="airport-origin" cx={ox} cy={oy} r="7"/><circle className="airport-destination" cx={dx} cy={dy} r="7"/><g className="route-aircraft" transform={`translate(${ox+(dx-ox)*.63} ${oy+(dy-oy)*.63}) rotate(${Math.atan2(dy-oy,dx-ox)*180/Math.PI})`}><Plane size={25}/></g><text x={ox-8} y={oy-16}>{route.origin.code}</text><text className="city-label" x={ox-8} y={oy+23}>{route.origin.name}</text><text x={dx+12} y={dy-5}>{route.destination.code}</text><text className="city-label" x={dx+12} y={dy+14}>{route.destination.name}</text></svg><div className="map-key"><span><i/>Scheduled</span><span><i className="proposed"/>Proposed</span><b>{route.distance_km.toLocaleString('en-IN')} km · {route.block_minutes}m block</b></div></div>}

function Movement({route,mode}:{route:PlannedRoute;mode:Mode}){const base=route.movement_segments;const segments=mode==='aircraft'?[{time:'06:42',place:route.origin.code,kind:'arrival',detail:`${route.aircraft.registration} inbound`},...base,{time:'12:05',place:route.destination.code,kind:'turn',detail:'Next rotation protected'}]:mode==='crew'?[{time:'07:52',place:`${route.origin.code} crew room`,kind:'available',detail:'Rest complete'},...base,{time:'13:00',place:`${route.destination.code} hotel`,kind:'rest',detail:'10h rest protected'}]:mode==='deadhead'?[{time:'05:40',place:'AMD',kind:'deadhead',detail:`6E213 to ${route.origin.code}`},{time:'07:20',place:route.origin.code,kind:'connect',detail:'77m connection'},...base]:base;return <>{segments.map((s,i)=><div className="journey-step" key={`${s.time}-${i}`}><time>{s.time}</time><i/><span><b>{s.place}</b><small>{s.kind} · {s.detail}</small></span>{i<segments.length-1&&<em/>}</div>)}</>}

export default function RouteWorkspace({flight,onFlight}:{flight:Flight;onFlight?:(f:Flight)=>void}){
 const[routes,setRoutes]=useState<PlannedRoute[]>([]),[selected,setSelected]=useState(flight.id),[mode,setMode]=useState<Mode>('flight'),[validation,setValidation]=useState<RouteValidation|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{api.routes().then(x=>{setRoutes(x.items);setSelected(current=>x.items.some(r=>r.flight_id===current)?current:(x.items[0]?.flight_id||''))}).catch(e=>setError(e instanceof Error?e.message:'Routes unavailable')).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(routes.some(r=>r.flight_id===flight.id)){setSelected(flight.id);setValidation(null)}},[flight.id,routes]);
 const route=useMemo(()=>routes.find(r=>r.flight_id===selected)||routes[0],[routes,selected]);
 const choose=(id:string)=>{setSelected(id);setValidation(null);api.flight(id).then(f=>onFlight?.(f)).catch(()=>{})};
 const validate=async()=>{setBusy(true);setError('');try{setValidation(await api.validateRoute(route.flight_id))}catch(e){setError(e instanceof Error?e.message:'Validation failed')}finally{setBusy(false)}};
 if(error&&!route)return <section className="empty"><AlertTriangle/><h2>Route network unavailable</h2><p>{error}</p><button onClick={()=>location.reload()}>Retry</button></section>;
 if(loading||!route)return <section className="empty"><RefreshCw className="spin"/><h2>Loading route network</h2><p>Reading current movement plans from operations API.</p></section>;
 return <><header className="page-head"><div><span>PLANNED ROUTES · INDIA NETWORK</span><h1>Movement feasibility and positioning</h1><p>Select any flight to inspect its own geographic route and movement chain.</p></div><div className="page-actions"><span className="badge cyan">INDIA DOMESTIC</span><button className="primary" disabled={busy} onClick={validate}>{busy?<><RefreshCw className="spin"/>Validating</>:validation?.legal?<><Check/>Backend validated</>:<>Validate movement chain</>}</button></div></header><div className="route-flight-strip">{routes.map(r=><button key={r.flight_id} className={r.flight_id===route.flight_id?'active':''} onClick={()=>choose(r.flight_id)}><Plane/><span><strong>{r.flight_id}</strong><small>{r.origin.code} → {r.destination.code}</small></span><b>{r.proposed.departure}</b></button>)}</div><div className="route-tabs">{modes.map(([id,label,Icon])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}><Icon/>{label}</button>)}</div><div className="routes-layout"><section><div className="geo-map"><div className="map-toolbar"><strong>{route.flight_id} · {route.origin.code} → {route.destination.code}</strong><span className={`badge ${validation?(validation.legal?'success':'danger'):'cyan'}`}>{validation?(validation.legal?'DGCA CHECKS PASS':'LEGALITY FINDING'):mode.toUpperCase()}</span></div><IndianMap route={route}/></div><section className="card route-details"><header><h2>Scheduled vs proposed operation</h2><span className="badge warning"><AlertTriangle/> {route.restriction}</span></header><div className="route-compare"><article><span>SCHEDULED</span><h3>{route.origin.code} {route.scheduled.departure} → {route.destination.code} {route.scheduled.arrival}</h3><p>{route.aircraft.type} · {route.aircraft.registration} · Crew {route.crew_id}</p></article><ArrowRight/><article><span>PROPOSED</span><h3>{route.origin.code} {route.proposed.departure} → {route.destination.code} {route.proposed.arrival}</h3><p>Direct routing · {route.distance_km.toLocaleString('en-IN')} km · current state</p></article></div></section></section><aside className="card journey"><header><div><h2>Operational movement</h2><small>{route.flight_id} · {route.aircraft.registration}</small></div><span className={`badge ${validation?.legal?'success':'cyan'}`}>{validation?.legal?'VALIDATED':'CURRENT'}</span></header><Movement route={route} mode={mode}/><div className="checks-block"><h3>Backend feasibility checks</h3>{validation?Object.entries(validation.checks).map(([name,pass])=><span key={name}><Check/>{name.replaceAll('_',' ')}<b>{pass?'Pass':'Fail'}</b></span>):<p>Run validation to check route continuity and DGCA-oriented legality against authoritative backend state.</p>}</div></aside></div></>
}
