import{useEffect,useState}from'react';
import{AlertTriangle,Check,Clock3,RefreshCw,ShieldCheck,Users}from'lucide-react';
import{api}from'./api';
import type{Recovery,Tier3Queue,Tier3Suggestion}from'./types';

export default function Tier3Workspace({recovery,onRecovery,onStart}:{recovery:Recovery|null;onRecovery:(r:Recovery)=>void;onStart:()=>void}){
 const[queue,setQueue]=useState<Tier3Queue|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=()=>{if(!recovery)return;setError('');api.tier3Suggestions(recovery.id).then(setQueue).catch(e=>setError(e.message))};
 useEffect(load,[recovery?.id,recovery?.state_version]);
 const act=async(s:Tier3Suggestion,action:'approve'|'reject'|'hold')=>{if(!recovery)return;const reason=action==='approve'?'Accepted for candidate generation':`${action==='hold'?'Held for supervisor review':'Rejected by scheduler'}`;setBusy(s.suggestion_id+action);setError('');try{const result=await api.decideTier3(recovery.id,s.suggestion_id,recovery.state_version,action,reason);onRecovery(result.recovery)}catch(e){setError(e instanceof Error?e.message:'Tier 3 action failed')}finally{setBusy('')}};
 if(!recovery)return <section className="empty"><Users/><h2>No active recovery</h2><p>Run the synthetic recovery first. Tier 3 is generated from cases that remain unresolved after automated tiers.</p><button className="primary" onClick={onStart}>Start recovery</button></section>;
 if(error&&!queue)return <section className="empty"><AlertTriangle/><h2>Tier 3 queue unavailable</h2><p>{error}</p><button onClick={load}>Retry</button></section>;
 return <><header className="page-head"><div><span>TIER 3 · HUMAN-ASSISTED RECOVERY</span><h1>Scheduler suggestion queue</h1><p>Legality-gated options require explicit review. Accepting an option creates a candidate; it does not approve or deploy it.</p></div><div className="page-actions"><span className="badge purple">{queue?.status?.toUpperCase()||'LOADING'}</span><button onClick={load}><RefreshCw/> Refresh</button></div></header>{error&&<div className="provenance"><AlertTriangle/><span><strong>Action not completed</strong><small>{error}</small></span></div>}{!queue?<section className="empty"><RefreshCw className="spin"/><h2>Loading queue</h2></section>:queue.items.length===0?<section className="empty"><ShieldCheck/><h2>No unresolved suggestions</h2><p>Automated tiers covered the current synthetic cases. Tier 3 remains available but has nothing requiring scheduler intervention.</p></section>:<div className="candidate-grid">{queue.items.map(s=><article className="candidate" key={s.suggestion_id}><header><span className="badge purple">RANK {s.rank}</span><strong>{s.status.replaceAll('_',' ').toUpperCase()}</strong></header><h2>{s.proposed_flight_ids.join(', ')}</h2><div className="score">{Math.round(s.confidence*100)}%<span>rule-based confidence</span></div><div className="candidate-metrics"><span>Crew<b>{s.crew_id}</b></span><span>Duty cost<b>{s.duty_time_cost.toFixed(1)}h</b></span><span>Benefit<b>{Math.round(s.operational_benefit*100)}%</b></span></div><div className="explain"><strong>Why this option</strong><p>{s.explanation}</p><small>{s.ruleset_version} · state v{s.state_version}</small></div>{s.residual_risks.map(r=><p key={r}><AlertTriangle/> {r}</p>)}{s.status==='pending'&&<div className="page-actions"><button disabled={!!busy} onClick={()=>act(s,'reject')}>Reject</button><button disabled={!!busy} onClick={()=>act(s,'hold')}><Clock3/> Hold</button><button className="primary" disabled={!!busy} onClick={()=>act(s,'approve')}><Check/> Accept as candidate</button></div>}</article>)}</div>}</>
}
